name: French Fire
shortName: French Fire
version: 1.0.0
lang: en
dir: ltr
display: standalone
orientation: any
description: "A GitHub repository for easily creating fast, modern, PWA compatible websites"
icons-file: /img/icons.svg
theme:
  color: '#008000'
  background: '#242424'
icons:
  - src: /img/favicon.svg
    type: image/svg+xml
    sizes: 150x150
    purpose: maskable any
  - src: /img/apple-touch-icon.png
    rel: apple-touch-icon
    type: image/png
    sizes: 180x180
  - src: /img/icon-512.png
    type: image/png
    sizes: 512x512
    purpose: maskable any
  - src: /img/icon-192.png
    type: image/png
    sizes: 192x192
    purpose: maskable any
  - src: /img/icon-32.png
    type: image/png
    sizes: 32x32
  - src: /img/icon-16.png
    type: image/png
    sizes: 16x16
screenshots:
  - src: 'https://i.imgur.com/IjdVouxh.png'
    sizes: 1024x502
    type: image/png
  - src: 'https://i.imgur.com/IjdVouxl.png'
    sizes: 640x314
    type: image/png
  - src: 'https://i.imgur.com/IjdVouxm.png'
    sizes: 320x157
    type: image/png
  - src: 'https://i.imgur.com/IjdVouxt.png'
    sizes: 160x78
    type: image/png
# https://web.dev/app-shortcuts/
shortcuts:
  - name: Pets
    description: Test article and shortcut
    url: /pets/
    icons:
    # - src: /img/shortcuts/pets.svg
    #   sizes: 192x192
    #   type: image/svg+xml
    - src: /img/shortcuts/pets-192.png
      sizes: 192x192
      type: image/png
    - src: /img/shortcuts/pets-144.png
      sizes: 144x144
      type: image/png
    - src: /img/shortcuts/pets-96.png
      sizes: 96x96
      type: image/png
    - src: /img/shortcuts/pets-72.png
      sizes: 72x72
      type: image/png
    - src: /img/shortcuts/pets-48.png
      sizes: 48x48
      type: image/png
    - src: /img/shortcuts/pets-36.png
      sizes: 36x36
      type: image/png
  - name: Contacts
    description: List of recent changes
    url: /contacts/
    icons:
    # - src: /img/shortcuts/contacts.svg
    #   sizes: 192x192
    #   type: image/svg+xml
    - src: /img/shortcuts/contacts-192.png
      sizes: 192x192
      type: image/png
    - src: /img/shortcuts/contacts-144.png
      sizes: 144x144
      type: image/png
    - src: /img/shortcuts/contacts-96.png
      sizes: 96x96
      type: image/png
    - src: /img/shortcuts/contacts-72.png
      sizes: 72x72
      type: image/png
    - src: /img/shortcuts/contacts-48.png
      sizes: 48x48
      type: image/png
    - src: /img/shortcuts/contacts-36.png
      sizes: 36x36
      type: image/png
    - name: Resources
  - name: News
    description: List of recent changes
    url: /news/
    icons:
    # - src: /img/shortcuts/news.svg
    #   sizes: 192x192
    #   type: image/svg+xml
    - src: /img/shortcuts/news-192.png
      sizes: 192x192
      type: image/png
    - src: /img/shortcuts/news-144.png
      sizes: 144x144
      type: image/png
    - src: /img/shortcuts/news-96.png
      sizes: 96x96
      type: image/png
    - src: /img/shortcuts/news-72.png
      sizes: 72x72
      type: image/png
    - src: /img/shortcuts/news-48.png
      sizes: 48x48
      type: image/png
    - src: /img/shortcuts/news-36.png
      sizes: 36x36
      type: image/png
# https://web.dev/web-share-target/
share_target:
  name: Contact Page
  action: /pets/report/#found
  enctype: multipart/form-data
  method: POST
  params:
    title: name
    text: description
    files:
      - name: image
        accept:
          - image/jpeg
          - image/png
          - .jpg
          - .jpeg
          - .png
# iarc_rating_id:
related_applications:
  - platform: webapp
    url: /webapp.webmanifest
  # - platform: play
  #   id: "twa.weather.kernvalley"
  #   url: "#"
  # - platform: itunes
  #   url: "#"
  # - platform: windows
  #   url: "#"
features:
  - PWA-ready GitHub template for Jekyll sites
  - Dark mode support, controlled by (prefers-color-scheme) media query
  - Includes templates created with SEO via structured data in mind
  - Initial setup scores 99% on mobile on Page Speed Insights
  - Responsive design supporting any screen size thanks to CSS grid and use of viewport units
  - Integtation with system sharing via the Share API (with fallback)
  - Preset Pull Request and Issue templates, as well as Code of Conduct & Contributing Guidelines
  - Built-in testing via GitHub Actions, eslint, and stylelint
  - Always up-to-date thanks to preset Dependabot-v2 config
  - Setup for quick deployment to Netlify
  - Version files for Ruby and NodeJS (.rvmrc, .ruby-version, and .nvmrc)
# https://github.com/w3c/manifest/wiki/Categories
categories:
  - news
  - utilities
