name: French Fire
shortName: French Fire
version: 1.0.0
lang: en
dir: ltr
display: standalone
orientation: any
description: Maps, news, info, and support for the French Fire in the Kern Valley
icons-file: /img/icons.svg
theme:
  color: '#008000'
  background: '#242424'
icons:
  - src: /img/favicon.svg
    type: image/svg+xml
    sizes: 150x150
    purpose: maskable any
  - src: /img/apple-touch-icon.png
    rel: apple-touch-icon
    type: image/png
    sizes: 180x180
  - src: /img/icon-512.png
    type: image/png
    sizes: 512x512
    purpose: maskable any
  - src: /img/icon-192.png
    type: image/png
    sizes: 192x192
    purpose: maskable any
  - src: /img/icon-32.png
    type: image/png
    sizes: 32x32
  - src: /img/icon-16.png
    type: image/png
    sizes: 16x16
screenshots:
  - src: https://i.imgur.com/kBNj4cMh.png
    sizes: 1024x497
    type: image/jpeg
  - src: https://i.imgur.com/kBNj4cMl.png
    sizes: 640x310
    type: image/jpeg
  - src: https://i.imgur.com/kBNj4cMm.png
    sizes: 320x155
    type: image/jpeg
  - src: https://i.imgur.com/kBNj4cMt.png
    sizes: 160x78
    type: image/jpeg
# https://web.dev/app-shortcuts/
shortcuts:
#   - name: Pets
#     description: Test article and shortcut
#     url: /pets/
#     icons:
#     # - src: /img/shortcuts/pets.svg
#     #   sizes: 192x192
#     #   type: image/svg+xml
#     - src: /img/shortcuts/pets-192.png
#       sizes: 192x192
#       type: image/png
#     - src: /img/shortcuts/pets-144.png
#       sizes: 144x144
#       type: image/png
#     - src: /img/shortcuts/pets-96.png
#       sizes: 96x96
#       type: image/png
#     - src: /img/shortcuts/pets-72.png
#       sizes: 72x72
#       type: image/png
#     - src: /img/shortcuts/pets-48.png
#       sizes: 48x48
#       type: image/png
#     - src: /img/shortcuts/pets-36.png
#       sizes: 36x36
#       type: image/png
  - name: Contacts
    description: List of recent changes
    url: /contacts/
    icons:
    # - src: /img/shortcuts/contacts.svg
    #   sizes: 192x192
    #   type: image/svg+xml
    - src: /img/shortcuts/contacts-192.png
      sizes: 192x192
      type: image/png
    - src: /img/shortcuts/contacts-144.png
      sizes: 144x144
      type: image/png
    - src: /img/shortcuts/contacts-96.png
      sizes: 96x96
      type: image/png
    - src: /img/shortcuts/contacts-72.png
      sizes: 72x72
      type: image/png
    - src: /img/shortcuts/contacts-48.png
      sizes: 48x48
      type: image/png
    - src: /img/shortcuts/contacts-36.png
      sizes: 36x36
      type: image/png
    - name: Resources
  - name: News
    description: List of recent changes
    url: /news/
    icons:
    # - src: /img/shortcuts/news.svg
    #   sizes: 192x192
    #   type: image/svg+xml
    - src: /img/shortcuts/news-192.png
      sizes: 192x192
      type: image/png
    - src: /img/shortcuts/news-144.png
      sizes: 144x144
      type: image/png
    - src: /img/shortcuts/news-96.png
      sizes: 96x96
      type: image/png
    - src: /img/shortcuts/news-72.png
      sizes: 72x72
      type: image/png
    - src: /img/shortcuts/news-48.png
      sizes: 48x48
      type: image/png
    - src: /img/shortcuts/news-36.png
      sizes: 36x36
      type: image/png
  - name: Fire Map
    description: Recent fire map of the French Fire
    url: /map/
    icons:
    # - src: /img/shortcuts/news.svg
    #   sizes: 192x192
    #   type: image/svg+xml
    - src: /img/shortcuts/map-192.png
      sizes: 192x192
      type: image/png
    - src: /img/shortcuts/map-144.png
      sizes: 144x144
      type: image/png
    - src: /img/shortcuts/map-96.png
      sizes: 96x96
      type: image/png
    - src: /img/shortcuts/map-72.png
      sizes: 72x72
      type: image/png
    - src: /img/shortcuts/map-48.png
      sizes: 48x48
      type: image/png
    - src: /img/shortcuts/map-36.png
      sizes: 36x36
      type: image/png
# https://web.dev/web-share-target/
share_target:
  name: Contact Page
  action: /pets/report/#found
  enctype: multipart/form-data
  method: POST
  params:
    title: name
    text: description
    files:
      - name: image
        accept:
          - image/jpeg
          - image/png
          - .jpg
          - .jpeg
          - .png
# iarc_rating_id:
related_applications:
  - platform: webapp
    url: /webapp.webmanifest
  # - platform: play
  #   id: "twa.weather.kernvalley"
  #   url: "#"
  # - platform: itunes
  #   url: "#"
  # - platform: windows
  #   url: "#"
features:
  - News, updates, and maps for the French Fire
  - Upcoming lost & found pet searching and reporting
  - A compiled list of various fire agencies, support and aid groups, etc.
  - Offline browsing support (certain pages and functionality)
  - Dark mode support
  - Integtation with system sharing via the Share API (with fallback)
# https://github.com/w3c/manifest/wiki/Categories
categories:
  - news
  - utilities
